exclude:
  - Gemfile
  - Gemfile.lock
baseurl: /service-handbook

markdown: kramdown
kramdown:
  input: GFM

collections:
  discovery:
    output: true
    name: Discovery
    sections:
      - 1-introduction
      - 2-starting-discovery
      - 3-finishing-discovery
      - 4-further-reading

  alpha:
    output: true
    name: Alpha
    sections:
      - 1-introduction
      - 2-getting-started
      - 3-building-prototypes
      - 4-finishing-alpha

  capability:
    output: true
    name: Capability
    sections:
      - 1-introduction
      - 2-multi
      - 3-tech

  inflight:
    output: true
    name: In-flight assessments
    sections:
      - 1-in-flight-assessments
      - 2-check-ins
      - 3-assessment-reviews
      - 4-delivery-stages
      - 5-tools

defaults:
  - scope:
      path: ""
    values:
      index: false
      section: null
      layout: main
