exclude:
  - Gemfile
  - Gemfile.lock
baseurl: /service-handbook
kramdown:
  input: GFM

collections:
  discovery:
    output: true

  alpha:
    output: true

defaults:
  - scope:
      type: discovery
      path: ""
    values:
      layout: main
      section: discovery

  - scope:
      type: alpha
      path: ""
    values:
      layout: main
      section: alpha

discovery_url: "#{baseurl}/discovery"
alpha_url: "#{baseurl}/alpha"
