exclude:
  - Gemfile
  - Gemfile.lock
baseurl: /service-handbook
kramdown:
  input: GFM

collections:
  discovery:
    output: true
    name: Discovery
    sections:
      - 1-introduction
      - 2-starting-discovery
      - 3-finishing-discovery
      - 4-further-reading

  alpha:
    output: true
    name: Alpha
    sections:
      - 1-introduction
      - 2-team
      - 3-during-alpha
      - 4-finishing-alpha

defaults:
  - scope:
      path: ""
    values:
      index: false
      section: null
      layout: main
